### ISSUE TITLE
Problem with RSS feed

### ISSUE THREAD

**Issue by aisejohan** [kerodon/kerodon-website#5]
At least my rss reader says: ` LibXML error 26 at line 4 (column 25): Entity 'ndash' not defined`

I am using tt-rss

**Comment by pbelmans** [comment]
Ah yes, I should not have used HTML entities in an XML document. Silly me!

It should be fixed now, and also it should be served with the correct MIME type now. Can you refresh your tt-rss and see whether it's working for you now?

**Comment by aisejohan** [comment]
All good
